### ISSUE TITLE
Consider getting rid of BytesMut in favor of only Bytes

### ISSUE THREAD

**Issue by carllerche** [carllerche/bytes#116]
Currently, `Bytes` represents an immutable, potentially shared, view into a memory region. `BytesMut` represents a unique view into a memory region, which means that the memory can be mutated.

Perhaps there is a way to collapse these two types into a single type.

**Pros**

* Less types

**Cons**

* Mutation may have to implicitly copy the memory into a new buffer... this expense may not be obvious. It may also be that extra runtime state may be needed to track if a handle has a unique view or not.

**Comment by alexcrichton** [comment]
Hm yeah so in some sense all "change the capacity" operations already run the risk of copying all the bytes (e.g. a realloc). As a result the major downside here to me is that otherwise cheap operations like `as_mut_slice` now have the potential to be expensive.

**Comment by stepancheg** [comment]
May I suggest an idea? Not sure it works, but still.

Drop `BytesMut` struct and introduce

```
struct BytesRefMut<'a> {
    bytes: &'a mut Bytes,
    begin: *mut u8, // valid pointer even if kind == KIND_INLINE
    len: usize,
    cap: usize
}

impl Drop for BytesMutRef {
    fn drop() {
        flush len if kind == KIND_INLINE
    }
}

impl Bytes {
    // deep copy if refcount > 1
    fn unshare(&mut self) -> BytesMutRef { ... }
}
```

* all mutation operations reside in `BytesMutRef` object
* refcounter is checked only in `unshare` operation (unlike mutation operation on `Bytes` object)
* `unshare` can be expensive (because of copying of buffer), but it is explicit now
* repeated `put_u8` operations are cheaper on `BytesMutRef` than on `BytesMut`, because kind is checked only twice (in `unshare` and in `drop`), not on each `put_u8`
* that object may have cheap `push` operation

**Comment by carllerche** [comment]
I don't think this idea will pan out. So, I'm going to close this issue.
