### ISSUE TITLE
Drop original capacity and implement truncate_front

### ISSUE THREAD

**Issue by stepancheg** [carllerche/bytes#122]
## Drop original_capacity

Currently bytes crate have a logic of preserving "original capacity" during split.

So

```
drop(bytes.take());
// `bytes` here will have original capacity preserved if original capacity was <= 16K
```

I'm not sure if this logic is actually useful, and it may be confusing (e. g. you got a 100 bytes buffer, you called `reserve(1)` and got 64K allocated).

I'd simply remove it (even without implementing `truncate_front`).

## Implement truncate_front

On the other hand, without "original capacity" field it would be possible to implement cheap `truncate_front` operation.

`truncate_front` is the same as `truncate`, but truncates from front, not from back.

`truncate_front` is implemented trivally for `KIND_ARC`, `KIND_STATIC` and `KIND_INLINE`.

And for `KIND_VEC` `truncate_front` can be implementing by changing `arc` field of `Inner` struct to store a pointer to original `Vec`.

So for `KIND_VEC`

```
struct Inner {
    arc: AtomicPtr<Shared>, // vec.as_mut()
    ptr: *mut u8, // position to current view
    len: usize, // len of current view
    cap: usize, // capacity to current view
}
``` 

So to reconstruct `Vec` from `Inner` (e. g. to convert to `Arc`) you could write something like:

```
fn reconstruct_vec(Inner inner) {
    debug_assert!(inner.kind() == KIND_VEC);
    let offset = inner.ptr - inner.arc;
    Vec::from_raw_parts(inner.arc, inner.len + offset, inner.cap + offset)
}
```

## Why truncate front

I believe there are lot of sitations when you need to take a `Bytes` and simply truncate front and back. For example, if you parse HTTP/2 frame, you can take `Bytes` by value, and truncate headers and padding to retrieve payload as `Bytes`. If `kind == KIND_VEC` this operation will be cheaper than currently with `split_off`, because `Bytes` won't need to be converted to `KIND_ARC`.

**Comment by carllerche** [comment]
The intention of tracking the original allocation size was to handle a regression when transitioning to `tokio-io`. Part of the problem is that `Decoder` don't know the size of the originally allocated buffer. So `Decoder` is expected to reserve only as much as is needed for the current frame, but then, you can get into a situation where tiny reallocations are required.

Being able to `truncate_front` would be nice... but I am unsure what the best trade off is...  At this point, removing the original capacity tracking would require either figuring out how to do so w/o it being a breaking change OR figure out a way to migrate off for tokio-io 0.2.

**Comment by stepancheg** [comment]
Shouldn't `FramedRead` store initial capacity explicitly, and use it in `reserve`, and do not rely on `Bytes` property of preserving capacity in `split_*` and `take` operations?

It should be a mostly backward-compatible change of tokio-io (it will be source-compatible, but behavior will change slighly), no need to wait for tokio-io 0.2.

**Comment by carllerche** [comment]
`FramedRead` does *not* call `reserve`. The `Decoder` impl calls `reserve` as needed.

**Comment by stepancheg** [comment]
Even if `Decoder` impl calls `reserve`, `FramedRead` could also call `reserve` before `read_buf` with initial capacity.

**Comment by carllerche** [comment]
How does `FramedRead` know when to call `reserve`? If it calls `reserve` w/ the initial capacity each "tick" then there is no point in using `Bytes` because every iteration will allocate a brand new chunk.

`Decoder` is the thing that knows when to call `reserve` correctly, but it doesn't know the "right" amount... `FramedRead` knows this.

**Comment by stepancheg** [comment]
OK, I think I got it.

`FramedRead` could call `reserve(initial_capacity)` right before `read_buf`. However, in that case it will be one unnecessary reallocation per `read_buf` if last `reserve` call in `Decoder` reserved less than `initial_capacity`.

So it is not possible to make this change without breaking/changing `tokio-io`.

**Comment by arthurprs** [comment]
Somewhat related, what's the cheapest way of "consuming" the first N bytes of Bytes right now?
I'm using split_off(..)

**Comment by stepancheg** [comment]
So, tokio-io `Decoder::decode` could be changed to something like:

```
// Ok(Ok(item)) means it was decoded successfully
// Ok(Err(44)) means that decoder needs 44 bytes to decode something
fn decode(&mut self, src: &mut BytesMut) -> Result<Result<Self::Item, usize>, Self::Error>;
```

And `FramedRead::poll` should do `reserve` with error value of inner result.

Right?

**Comment by carllerche** [comment]
Technically, yes. However, the goal of `Encoder` and `Decoder` is to be as simple as possible. I think we already have strayed from that goal too much.

**Comment by stepancheg** [comment]
Closing this issue in favor of tokio-io issue I've just created.
