### ISSUE TITLE
Make Buf / MutBuf bytes() function unsafe

### ISSUE THREAD

**Issue by carllerche** [carllerche/bytes#13]
Since it is possible to access uninitialized memory using these functions, they should be unsafe.

**Comment by fhartwig** [comment]
I've noticed this as well (didn't report it because I wasn't sure that accessing uninitialised bytes falls under rust's definition of "unsafe") about `MutBuf::bytes`. I'm don't understand how `Buf::bytes` is unsafe though. How can you access uninitialised memory through it (without abusing `MutBuf`'s `advance`)?

**Comment by carllerche** [comment]
I believe you are correct re: `Buf::bytes()`. I just made this issue as a reminder without thinking too much about it. I should probably tackle this soon though.

**Comment by carllerche** [comment]
This was done.
