### ISSUE TITLE
Add u128/i128 support with a feature

### ISSUE THREAD

**Issue by PlasmaPower** [carllerche/bytes#190]
I'm specifically referring to the methods in the `BufMut` trait.

`byteorder` already supports this so it shouldn't be too hard to add.

**Comment by termhn** [comment]
👍

**Comment by PlasmaPower** [comment]
The one problem is that currently, there's no way to make a dependency's feature conditional on your crate's feature. That means that we couldn't use byteorder's i128 feature, so we'd have to implement it in terms of i64/u64.

**Comment by carllerche** [comment]
It looks like this landed in 1.26.0, so in ~3 mo, the API can be added.

It's also possible it could be added gated w/ a feature flag before then.

**Comment by KodrAus** [comment]
I'd love support for this now, so can put together a PR for this gated by an `i128` feature flag.

**Comment by KodrAus** [comment]
Hmm, actually a feature flag might be problematic because these are methods on traits, so adding them through a feature could lead to random build failures depending on what libs you pull in. It's probably easier to just add this when you're ready.

In the meantime I can use an extension trait in my code.

**Comment by carllerche** [comment]
This was done.

**Comment by KodrAus** [comment]
@carllerche Did you have plans to publish a new `0.4.x` point release with the 128bit number support?

**Comment by carllerche** [comment]
It should be part of 0.4.9.
