### ISSUE TITLE
Advice needed: Bytes + Mmap

### ISSUE THREAD

**Issue by luben** [carllerche/bytes#191]
Hi,

I am using memmap crate and Rc/Arc guarded read-only Mmap buffers and Cow views into the buffers to do zero-copy IO/processing from the files. I noticed the approach greatly overlaps with the Bytes purpose (the zero-copy processing) and most probably I will need to copy into Bytes representation down the path for interacting with Tokio.

From a cursory look at Bytes, it look like the best strategy for me is to replace my IOBuff with Bytes as they will provide the required Rc behavior but I don't know how I can plug the Mmap-ed buffers into Buf/Bytes? May be create a wrapper for the Mmap buffers and implement Buf for it? Any suggestions will be greatly appreciated.

For reference here is my current structure:

```rust
  /// Abstract IO byte buffers, i.e. everything that can be
  /// dereferenced as [u8]. It is intended to be used with
  /// `String`s, `&str` and `MMap`s.
  ///
  /// Going through trait object adds one pointer indirection
  /// but it will not happen at the processing time as the
  /// string representation Cow<str> indexes directly in
  /// the backing buffer.
  #[derive(Clone)]
  pub struct IOBuff {
      // reference count the buffers in order to automatically
      // free them up when the last reference vanishes
      buff: Rc<Deref<Target = [u8]>>,
      // files are mmaped on page boundaries so we have to
      // keep skip offset of the logical start of the payload
      skip: usize,
  }
  
  // impl IOBuff
  // impl Deref for IOBuff
  // impl From<Vec<u8>> for IOBuff
  // ... 

  impl<'a> From<Mmap> for IOBuff {
      fn from(mmap: Mmap) -> IOBuff {
          IOBuff {
              buff: Rc::new(mmap),
              skip: 0,
          }
      }
  }
```

**Comment by carllerche** [comment]
A mmap type would not integrate with `Bytes` as there are no hooks for allocate / deallocate. Instead, I would recommend implementing the `Buf` and `BufMut` traits. This is the primary integration point for different "byte storage" implementations.

Hope this helps. I'm going to close this, but feel free to post additional comments.

**Comment by federicomenaquintero** [comment]
The problem with implementing `Buf` for `Mmap` is that the whole buffer will get copied into a `Bytes`.  I think @luben wants to implement a pattern where one mmaps a file, and then extracts slices from it as the big buffer gets parsed.

Let's say you have a binary file with a structure something like this:

```
field            size

magic            4 bytes
num_items        8 bytes
item0_offset     8 bytes
item1_offset     8 bytes
...
item0_size       8 bytes
item0_data       [from item0_size]

item1_size       8 bytes
item1_data       [from item1_size]
...
```

Then, one could have a representation like this:
```rust
struct MyThing {
    the_whole_buffer: Bytes,
    magic: Bytes,
    items: Vec<Bytes>
}
```

However, one would like to avoid `the_whole_buffer` being a copy of a big `Mmap` buffer!  It would be very useful to have a function in Bytes similar to

```rust
fn from_byte_buffer<T>(b: T) -> Bytes
    where T: Deref<Target = [u8]>
```

`Mmap` from the `memmap` crate is `Deref<Target=[u8]>`.  The `from_byte_buffer()` function would effectively mean, "please become the owner of this thing which can present itself as a byte slice, and give me a Bytes around it".

(Backstory: I was working on a crate that would process memory-mapped files.  Since one cannot have self-referential structs, it is *really* inconvenient to litter the code with lifetimes everywhere, for example, to have the `magic` and `items` from `MyThing` above as normal Rust slices.  For the purpose of that crate, it was much better to use a big `Bytes` and get smaller `Bytes` slices out of it, since they hide the need for lifetimes.  My crate had the problem that to create the intial `Bytes`, one had to copy the entire memory-mapped file into it first, which sort of defeats the purpose of mmap()).

**Comment by luben** [comment]
@federicomenaquintero , yes this is exactly my case, I create a self-referential struct by parsing a mmaped file and wanted to get rid of the lifetime tracking. BTW, in you example, you don't need `the_whole_buffer` to be part of the struct as it is going to be kept alive by the elements referencing it but you are right that you need to create it first (by copy) and that defeats the mmaping.

**Comment by carllerche** [comment]
@federicomenaquintero The `Buf` trait does not require loading everything into memory. It is a trait that represents iterating over bytes. It can be thought of as a specialized version of `Iterator` but for byte slices.

The `Bytes` type will not allow configurable sources of memory. That is not its purpose.

The purpose of `Bytes` is to provide byte storage that has cheap clones (shallow copy). The `Buf` trait is to allow programming over generic byte storage.

**Comment by luben** [comment]
@carllerche , @federicomenaquintero , I was looking closer at how to bridge `memmaps` and `bytes` and I got another idea, may be not feasible so wanted to bounce it for review:

1. Create `MmapBytes` newtype wrapper
2. Implement `Deref` for `MmapBytes` that delegates to `Mmap`'s `Deref` returning `[u8]`
3. Implement `From` for `MmapBytes` into Bytes (read-only) where we create new `Vec<u8>` from the underlying mmap slice, and then wrap it in `Bytes`

I think it will potentially solve both problems that we discussed:

1. Zero copy
2. Bytes will be reference counted so we don't need to track the lifetimes

@federicomenaquintero, is this going to fit also your use case?

Any suggestions are welcome.
