### ISSUE TITLE
Documentation is vague concerning use cases

### ISSUE THREAD

**Issue by hlb8122** [carllerche/bytes#246]
From the outside it's not inherently clear when to use `Bytes` and when to use bare u8 arrays/vectors.

The documentation briefly mentions: 

> It is intended for use primarily in networking code, but could have applications elsewhere as well.

Why is it favoured in networking code? Because of its interaction with buffers? Because it plays nice with libraries like tokio? Is it worth using in entirely single threaded code? If your byte stores are small does it become poor choice even with the inline byte optimization?

Replacing your existing byte stores with `Bytes` and then benchmarking is the obvious solution but is time consuming and can require some non-trivial changes. It'd be nice to have more detailed guidelines concerning the overheads and under what circumstances they are negated etc.

**Comment by carllerche** [comment]
The primary difference is that `Bytes` does shallow clones. Many handles can point to different ranges within the same inner storage.

You can think of it as:

```rust
struct Bytes {
    data: Arc<Vec<u8>>,
    start: usize,
    len: usize,
```

Make sense?

I would be happy to accept a doc PR that elaborates.

**Comment by seanmonstar** [comment]
> Why is it favoured in networking code?

Some reasons is because data received over a network usually isn't altered much, but it frequently can be framed, or need to be sliced into smaller pieces.

For example, in HTTP, a single `tcp.read()` could mean you get the headers and body together. You likely want to split each header into its own data type, like `http::HeaderName` and `http::HeaderValue`. And then you want to take the last bit and represent a body. `Bytes` allows you to slice each of these with just a reference count, instead of needing to allocate a bunch of `Vec<u8>`s and copy into them.

----

Some situations it may make less sense in:

- In a text editor, since you need to quickly mutate text at different places, and the file could be several megabytes (or even a couple gigs) big. In this case, you may want some sort of Rope structure instead.
- In an application where you never need to make sub slices, then you'll never benefit from the easy reference count in `Bytes`. May as well just use a `Vec<u8>`...

**Comment by dekellum** [comment]
Possibly off topic, feel free to ignore me… 

I've been trying to understand the design differences between `Bytes` and servo's `Tendril` (I think there might be a ByteTendril type or its generic for that.)  Anyone know enough about the later to comment on that?
